patterns:
  banner:
    fields:
      - name: heading
        type: string
        example: "Style with Kyle"
      - name: text
        type: string
        example: "Shop all: jeans, boots, accessories and more"

patterns:
  banner:
    fields:
      - name: button_text
        type: string
        example: "Shop Now"
        required: false
      - name: button_url
        type: url
        example: "/shop/"
        required: false
