patterns:
  banner:
    fields:
      - name: heading
        type: string
        example: "Style with Kyle"
      - name: text
        type: string
        example: "Shop all: jeans, boots, accessaries and more"
