patterns:
  banner:
    fields:
      - name: heading
        type: string
        example: "Style with Kyle"
      - name: text
        type: string
        example: "Jeans, boots, accessaries and more"
